### ISSUE TITLE
安装了qiniu 还是 报错 No module named 'qiniu' 

### ISSUE THREAD

**Issue by hiekay** [fy0/Icarus#10]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from lib import mail, qn
  File "./lib/qn.py", line 3, in <module>
    import qiniu
ModuleNotFoundError: No module named 'qiniu'

**Comment by fy0** [comment]
大概是你pipenv中的本地环境没有qiniu吧，不过讲道理按照部署文档走一遍应该没问题啊？
