### ISSUE TITLE
启动后端服务时报错 ImportError: cannot import name 'EMPTY_PERMISSION'`

### ISSUE THREAD

**Issue by ganichiro** [fy0/Icarus#25]
修改完private.py后再次运行
`python main.py`
报错：
`Traceback (most recent call last):`
`  File "main.py", line 3, in <module>`
`    from app import app`
`  File ".\app.py", line 1, in <module>`
`    from slim import Application, CORSOptions, EMPTY_PERMISSION`
`ImportError: cannot import name 'EMPTY_PERMISSION'`
`ModuleNotFoundError: No module named 'slim'`
疑似发生circular dependency imports
我用的是Windows10，anaconda python3.6.5

**Comment by lybing** [comment]
我运行提示：
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from app import app
  File "./app.py", line 1, in <module>
    from slim import Application, CORSOptions
ModuleNotFoundError: No module named 'slim'

**Comment by fy0** [comment]
emmmmm 之前requirements里的slim版本太旧了，导致了问题，最近更新了，还在抽空写文档。
@lybing 你没安装requirements。我觉得我还是弄个dockerfile吧 这样简单些

**Comment by ganichiro** [comment]
> emmmmm 之前requirements里的slim版本太旧了，导致了问题，最近更新了，还在抽空写文档。
> @lybing 你没安装requirements。我觉得我还是弄个dockerfile吧 这样简单些

多谢，搞个dockerfile会很有帮助。

**Comment by lybing** [comment]
> emmmmm 之前requirements里的slim版本太旧了，导致了问题，最近更新了，还在抽空写文档。
> @lybing 你没安装requirements。我觉得我还是弄个dockerfile吧 这样简单些
  好的，感谢，还是搞个dockerfile方便些，不然我这种弱前端的要搞不少东西，太费劲了
