### ISSUE TITLE
Windows下验证错误但用户已创建且已更改密码

### ISSUE THREAD

**Issue by justghostof** [fy0/Icarus#6]
c:\Icarus\backend>python3 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from model.redis import init as redis_init
  File "c:\Icarus\backend\model\__init__.py", line 22, in <module>
    asyncpg_init(config.DATABASE_URI)
  File "c:\Icarus\backend\model\__init__.py", line 19, in asyncpg_init
    async_run(create_conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\slim\utils\async_run.py", line 20, in async_run
    return loop.run_until_complete(func())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asynci
o\base_events.py", line 573, in run_until_complete
    return future.result()
  File "c:\Icarus\backend\model\__init__.py", line 17, in create_conn
    asyncpg_conn = await asyncpg.connect(db_uri)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\asyncpg\connection.py", line 1688, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\asyncpg\connect_utils.py", line 543, in _connect
    connection_class=connection_class)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\asyncpg\connect_utils.py", line 519, in _connect_addr
    await asyncio.wait_for(connected, loop=loop, timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asynci
o\tasks.py", line 416, in wait_for
    return fut.result()
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user
 "postgres"

**Comment by fy0** [comment]
我这里Windows下无问题，请给出更详细的描述，例如按照部署文档做到哪一步，然后出了什么状况。

根据你的错误日志，我只能知道试图验证PostgreSQL的postgres帐户失败，但是根据脚本逻辑，理论上这时应该自动创建了`private.py`，并试图登录Icarus帐户。

这让我有点搞不明白，请给出更详细的内容，以便于解决问题。
